_wandb:
    value:
        cli_version: 0.25.0
        e:
            lp9i7dz4c7k4io5c2oytqbso6ci4ewzl:
                args:
                    - --dataset
                    - mnist
                    - --epochs
                    - "5"
                    - --batch_size
                    - "64"
                    - --learning_rate
                    - "0.001"
                    - --optimizer
                    - rmsprop
                    - --activation
                    - sigmoid
                    - --hidden_layers=128
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 4
                cpu_count_logical: 8
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "554224840704"
                        used: "441286811648"
                email: mallelasindhuja@gmail.com
                executable: C:\Users\malle\anaconda3\envs\my_conda_env\python.exe
                gpu: Quadro P520
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Pascal
                      cudaCores: 384
                      memoryTotal: "4294967296"
                      name: Quadro P520
                      uuid: GPU-14118bf7-0f72-ba32-983a-49d7b0ad7d63
                host: SindhujaMallela
                memory:
                    total: "16942211072"
                os: Windows-11-10.0.26200-SP0
                program: C:\Users\malle\Desktop\da6401_assignment_1-main\da6401_assignment_1-main\src\train.py
                python: CPython 3.13.7
                root: C:\Users\malle\Desktop\da6401_assignment_1-main\da6401_assignment_1-main\src
                startedAt: "2026-03-07T14:02:26.974903Z"
                writerId: lp9i7dz4c7k4io5c2oytqbso6ci4ewzl
        m: []
        python_version: 3.13.7
        t:
            "2":
                - 2
                - 3
                - 5
                - 49
                - 53
            "3":
                - 16
            "4": 3.13.7
            "5": 0.25.0
            "8":
                - 3
            "12": 0.25.0
            "13": windows-amd64
activation:
    value: sigmoid
batch_size:
    value: 64
dataset:
    value: mnist
epochs:
    value: 5
hidden_layers:
    value:
        - 128
learning_rate:
    value: 0.001
loss:
    value: cross_entropy
model_save_path:
    value: models/
num_neurons:
    value: 128
optimizer:
    value: rmsprop
wandb_project:
    value: DL_Assign_1_proj
weight_init:
    value: xavier
